### ISSUE TITLE
nosetests code/trlda failure

### ISSUE THREAD

**Issue by zenzang** [lucastheis/trlda#3]
Hi Lucas, I successfully built and installed trlda with Python 2.7.13 and Numpy 1.12.1 (Python 2.7.13 :: Anaconda 4.4.0 (64-bit) on Ubuntu 16.04 LTS). But when I try to run nosetests code/trlda, it comes two errors. Any idea why this is happening.

```nosetests code/trlda
EE
======================================================================
ERROR: Failure: ImportError (/home/zen/anaconda2/lib/python2.7/site-packages/_trlda.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zen/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/zen/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/zen/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/media/zen/C4143FC6143FB9EE/Users/jason/Desktop/LDA-code/trlda-master/code/trlda/python/models/__init__.py", line 1, in <module>
    from _trlda import Distribution
ImportError: /home/zen/anaconda2/lib/python2.7/site-packages/_trlda.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

======================================================================
ERROR: Failure: ImportError (/home/zen/anaconda2/lib/python2.7/site-packages/_trlda.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zen/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/zen/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/zen/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/media/zen/C4143FC6143FB9EE/Users/jason/Desktop/LDA-code/trlda-master/code/trlda/python/utils/__init__.py", line 10, in <module>
    from _trlda import random_select
ImportError: /home/zen/anaconda2/lib/python2.7/site-packages/_trlda.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

----------------------------------------------------------------------
Ran 2 tests in 0.200s
```

**Comment by zenzang** [comment]
The problem stems for the fact that all my anaconda libs come pre-compiled with some unknown gcc version, and trlda is compiled with you system's gcc. Ubuntu 16.04 has gcc 5.4, so I downgrade it to gcc 4.8 and then it works fun.

**Comment by lucastheis** [comment]
Great! Let me know if you have any other issues.
